---
title: "Spatial_Correction"
author: "Leah Treffer"
date: "2025-11-23"
output: html_document
---

Add AIC

```{r include=FALSE}
library(tidyverse)
install.packages("here")
library(here)
library(multcompView)
library(lmerTest)
library(lme4)
library(lmtest)
library("PerformanceAnalytics")
library(dplyr)
library(broom.mixed)
library(emmeans)
library(metan)
library(purrr)
library(tidyr)
install.packages("lsmeans")
library("multcomp")
install.packages('sommer')
library(sommer)
```

```{r setup, include=FALSE}
knitr::opts_knit$set(root.dir = here::here())
```

```{r}
data <- read.csv('data/Intermediate/data_shared_across_locations_transformed.csv')
```

```{r}
data2 <- data %>%
  mutate(selected_cat = as.factor(case_when(
    selected == "selected" ~ "selected",
    selected == "base" ~ "base",
    TRUE ~ "other"
  )))%>%
  mutate(selected_cat2 = as.factor(case_when(
    selection_location == "WI" ~ "selectWI",
    selection_location == "KS" ~ "select",
    selection_location == "MN" ~ "select",
    selected == "base" ~ "base",
    TRUE ~ "other"
  )))%>%
  mutate(trial = as.character(case_when(
    LOC == "KS" ~ "A",
    LOC == "WI" ~ "B", 
    LOC == "NY" ~ "C"
  )))
```

```{r}
#data2 <- data2 |>
#  dplyr::group_by(trial) |>
#  dplyr::mutate(
#    Row2 = as.integer(factor(Row)),
#    Col2 = as.integer(factor(Col))
#  ) |>
#  ungroup()
```

```{r}
data2$LOC <- as.factor(data2$LOC)
data2$Entry <- as.factor(data2$Entry)
data2$Rep <- as.factor(data2$Rep)
data2$R <- as.factor(data2$Row)
data2$C <- as.factor(data2$Col)
data2$selected <- as.factor(data2$selected)
data2$selection_location <- as.factor(data2$selection_location)
data2$selected_type <- as.factor(data2$selected_type)
data2$selected_cat <- as.factor(data2$selected_cat)
data2$selected_cat2 <- as.factor(data2$selected_cat2)
data2$trial <- as.character(data2$trial)
data2$Row2 <- as.numeric(data2$Row2)
data2$Col2 <- as.numeric(data2$Col2)
```

```{r}
# lmer model : model <- lmer(First_Summer_ALF_Biomass_sqrt ~ Entry*LOC + (1|LOC:Rep), data=data)
# as a fixed effect, estimates the change in biomass associated with that Entry, that location, and the GxE
# If changed to a random effect, estimates predicted biomass of the entry

# SOMMER MODEL
mix2 <- mmes(First_Summer_ALF_Biomass_sqrt~Entry:LOC,
            random=~ R + C +
            random=~ spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
summary(mix2)
# does not work
# warning: solve(): system is singular; attempting approx solution
# Error: addition: incompatible matrix dimensions: 87x87 and 268x268
```

R and C unique by trial 
try without R and C
I think that an entry must be present in each location 

```{r}
mix2 <- mmes(First_Summer_ALF_Biomass_sqrt~Entry:LOC,
            random=~ spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
summary(mix2)
#warning: solve(): system is singular; attempting approx solution
#Error: addition: incompatible matrix dimensions: 88x88 and 268x268
```

```{r}
mix <- mmes(First_Summer_ALF_Biomass_sqrt~Entry,
            random=~ R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
summary(mix)$varcomp
# fixed effect estimates
summary(mix)$beta
# works but missing replicate and interaction 

Null <- mmes(First_Summer_ALF_Biomass_sqrt~1,
            random=~ R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
summary(Null)$beta

# LRT for entry
ll_full <- mix$llik[1, ncol(mix$llik)]
ll_null <- Null$llik[1, ncol(Null$llik)]
LR <- 2 * (ll_full - ll_null)
df <- nlevels(data2$Entry) - 1
pchisq(LR, df = df, lower.tail = FALSE)
rm(mix,Null,ll_full,ll_null,LR,df)
```

```{r}
mix3 <- mmes(First_Summer_ALF_Biomass_sqrt~Entry,
            random=~spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
summary(mix3)
# works but missing interaction 

Null <- mmes(First_Summer_ALF_Biomass_sqrt~1,
            random=~spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
summary(Null)$beta

# LRT for entry
ll_full <- mix3$llik[1, ncol(mix3$llik)]
ll_null <- Null$llik[1, ncol(Null$llik)]
LR <- 2 * (ll_full - ll_null)
df <- nlevels(data2$Entry) - 1
pchisq(LR, df = df, lower.tail = FALSE)
rm(mix3,Null,ll_full,ll_null,LR,df)
```




# spatial within location

```{r}
newyork <- data2[data2$LOC == "NY",]
newyork$Entry <- droplevels(newyork$Entry) # NY doesn't have IWAF-H-KS2

mix2 <- mmes(First_Summer_ALF_Biomass_sqrt~Entry,
            random=~ R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=newyork)
summary(mix2)
# varience component
summary(mix2)$varcomp
# fixed effect estimates
summary(mix2)$beta

Null <- mmes(First_Summer_ALF_Biomass_sqrt~1,
            random=~ R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=newyork)
summary(Null)$beta

# LRT for entry
ll_full <- mix2$llik[1, ncol(mix2$llik)]
ll_null <- Null$llik[1, ncol(Null$llik)]
LR <- 2 * (ll_full - ll_null)
df <- nlevels(newyork$Entry) - 1
pchisq(LR, df = df, lower.tail = FALSE)
rm(mix2,Null,ll_full,ll_null,LR,df)
```

```{r}
wisconsin <- data2[data2$LOC == "WI",]
wisconsin$Entry <- droplevels(wisconsin$Entry) # WI has fewer entries than other locations

mix2 <- mmes(First_Summer_ALF_Biomass_sqrt~Entry,
            random=~ R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=wisconsin)
summary(mix2)
# varience component
summary(mix2)$varcomp
# fixed effect estimates
summary(mix2)$beta

Null <- mmes(First_Summer_ALF_Biomass_sqrt~1,
            random=~ R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=wisconsin)
summary(Null)$beta

# LRT for entry
ll_full <- mix2$llik[1, ncol(mix2$llik)]
ll_null <- Null$llik[1, ncol(Null$llik)]
LR <- 2 * (ll_full - ll_null)
df <- nlevels(wisconsin$Entry) - 1
pchisq(LR, df = df, lower.tail = FALSE)
rm(mix2,Null,ll_full,ll_null,LR,df)
```

```{r}
kansas <- data2[data2$LOC == "KS",]
kansas$Entry <- droplevels(kansas$Entry) # drop unused levels to fit matrix
kansas$R <- droplevels(kansas$R)
kansas$C <- droplevels(kansas$C)

mix2 <- mmes(First_Summer_ALF_Biomass_sqrt~Entry,
            random=~ R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=kansas)
summary(mix2)
# varience component
summary(mix2)$varcomp
# fixed effect estimates
summary(mix2)$beta

Null <- mmes(First_Summer_ALF_Biomass_sqrt~1,
            random=~ R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=kansas)
summary(Null)$beta

# LRT for entry
ll_full <- mix2$llik[1, ncol(mix2$llik)]
ll_null <- Null$llik[1, ncol(Null$llik)]
LR <- 2 * (ll_full - ll_null)
df <- nlevels(kansas$Entry) - 1
pchisq(LR, df = df, lower.tail = FALSE)
rm(mix2,Null,ll_full,ll_null,LR,df)
```








```{r}
# SOMMER MODEL
mix <- mmes(First_Summer_ALF_Biomass_sqrt~1,
            random=~ Entry:LOC + R + C +
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
summary(mix)

```

```{r}
Estimates <- summary(mix)$beta %>%
  rownames_to_column(var = "Entry")
```

```{r}
data3 <- merge(data2, Estimates[,c("Entry", "Estimate")], by = "Entry")
```



```{r}
mix <- mmes(First_Summer_ALF_Biomass_sqrt~Entry*LOC,
            random=~ R + C + Rep + 
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
summary(mix)
# fixed effect estimates
summary(mix)$beta

mix2 <- mmes(First_Summer_ALF_Biomass_sqrt~Entry*LOC,
            random= ~rep2,
            rcov=~units, verbose=FALSE,
            data=data2)

mix <- mmes(First_Summer_ALF_Biomass_sqrt~Entry,
            random=~ R + C + Rep + 
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)

```


```{r}
# Is there a Significant Difference Among Entries
# Entries as random effect
mA <- mmes(First_Summer_ALF_Biomass_sqrt~LOC,
            random=~ Entry + R + C + Rep + 
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
# Null model
m0 <- mmes(First_Summer_ALF_Biomass_sqrt~LOC,
            random=~ R + C + Rep + 
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)

anova(m0, mA)

```

```{r}
# Is there a Significant Difference Among Entries
# Entries as fixed effect
mA <- mmes(First_Summer_ALF_Biomass_sqrt~Entry + LOC,
            random=~ R + C + Rep + 
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
# Null model
m0 <- mmes(First_Summer_ALF_Biomass_sqrt~LOC,
            random=~ R + C + Rep + 
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)

anova(m0, mA)

```

```{r}
# Is there a Significant Difference Among Locations
mA <- mmes(First_Summer_ALF_Biomass_sqrt~Entry*LOC,
            random=~  R + C + Rep + 
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
m0 <- mmes(First_Summer_ALF_Biomass_sqrt~Entry + LOC,
            random=~  R + C + Rep + 
              spl2Dc(Row2, Col2, at.var = trial),
            rcov=~units, verbose=FALSE,
            data=data2)
anova(m0, mA)
```


